services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    ports:
      - "${ZOOKEEPER_CLIENT_PORT}:${ZOOKEEPER_CLIENT_PORT}"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}

      # Step 1: Define how different logical listener names map to security protocols
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      
      # Step 2: Define the actual listeners and the ports they listen on *inside the container*
      # INTERNAL listener for other containers within the Docker network
      # EXTERNAL listener for access from the host network (mapped to 9092)
      KAFKA_LISTENERS: INTERNAL:${KAFKA_LISTENERS_1},EXTERNAL:${KAFKA_LISTENERS_2}
      
      # Step 3: Advertise these listeners with their appropriate hostnames/IPs and ports
      # INTERNAL listener advertised for other Docker containers
      # EXTERNAL listener advertised for the host-mode container via localhost
      KAFKA_ADVERTISED_LISTENERS: INTERNAL:${KAFKA_ADVERTISED_LISTENERS_1},EXTERNAL:${KAFKA_ADVERTISED_LISTENERS_2}

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      KAFKA_CREATE_TOPICS: "speak:1:1,environment:1:1,device:1:1,user:1:1,google:1:1"
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  service-user:
    build: ./services/service_user
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_started
    environment:
      - MYSQL_DATABASE_URL=${MYSQL_DATABASE_URL}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS_1}
      - ALFR3D_ENV_NAME=${ALFR3D_ENV_NAME}

  service-device:
    build: ./services/service_device
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_started
    network_mode: host  # To allow arp-scan on host network
    environment:
      - MYSQL_DATABASE_URL=localhost
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS_2}
      - ALFR3D_ENV_NAME=${ALFR3D_ENV_NAME}

  service-environment:
    build: ./services/service_environment
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_started
    environment:
      - MYSQL_DATABASE_URL=${MYSQL_DATABASE_URL}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS_1}
      - ALFR3D_ENV_NAME=${ALFR3D_ENV_NAME}

  service-daemon:
    build: ./services/service_daemon
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_started
    environment:
      - MYSQL_DATABASE_URL=${MYSQL_DATABASE_URL}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS_1}
      - ALFR3D_ENV_NAME=${ALFR3D_ENV_NAME}

  service-frontend:
    build: ./services/service_frontend
    depends_on:
      mysql:
        condition: service_started
      kafka:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE_URL=${MYSQL_DATABASE_URL}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS_1}
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1

volumes:
  mysql_data: