services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
    ports:
      - "${ZOOKEEPER_CLIENT_PORT}:${ZOOKEEPER_CLIENT_PORT}"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL:${KAFKA_LISTENERS_1},EXTERNAL:${KAFKA_LISTENERS_2}
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL:${KAFKA_ADVERTISED_LISTENERS_1},EXTERNAL:${KAFKA_ADVERTISED_LISTENERS_2}
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      - KAFKA_CREATE_TOPICS=speak:1:1,environment:1:1,device:1:1,user:1:1,google:1:1,event-stream:1:1,situational-awareness:1:1
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PSWD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  service-user:
    build: ./services/service_user
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_started
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PSWD=${MYSQL_PSWD}
      - MYSQL_NAME=${MYSQL_NAME}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS_1}
      - ALFR3D_ENV_NAME=${ALFR3D_ENV_NAME}

  service-api:
    build: ./services/service_api
    depends_on:
      mysql:
        condition: service_started
      kafka:
        condition: service_healthy
    ports:
      - "5001:5001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PSWD=${MYSQL_PSWD}
      - MYSQL_NAME=${MYSQL_NAME}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS_1}
      - ALFR3D_ENV_NAME=${ALFR3D_ENV_NAME}

  service-device:
    build: ./services/service_device
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_started
    network_mode: host  # To allow arp-scan on host network
    environment:
      - MYSQL_DATABASE=localhost
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PSWD=${MYSQL_PSWD}
      - MYSQL_NAME=${MYSQL_NAME}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS_2}
      - ALFR3D_ENV_NAME=${ALFR3D_ENV_NAME}

  service-environment:
    build: ./services/service_environment
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_started
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PSWD=${MYSQL_PSWD}
      - MYSQL_NAME=${MYSQL_NAME}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS_1}
      - ALFR3D_ENV_NAME=${ALFR3D_ENV_NAME}

  service-daemon:
    build: ./services/service_daemon
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_started
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PSWD=${MYSQL_PSWD}
      - MYSQL_NAME=${MYSQL_NAME}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS_1}
      - ALFR3D_ENV_NAME=${ALFR3D_ENV_NAME}

  service-frontend:
    build:
      context: ./services/service_frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}

  test-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: testrootpassword
      MYSQL_DATABASE: test_alfr3d_db
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data: