apiVersion: v1
kind: ConfigMap
metadata:
  name: alfr3d-k8s-env
data:
   MYSQL_ROOT_PASSWORD: "rootpassword"
   MYSQL_DATABASE: "alfr3d_db"
   MYSQL_USER: "user"
   MYSQL_PASSWORD: "password"
   KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
   KAFKA_BROKER_ID: "1"
   KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
   KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
   KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
   MYSQL_DATABASE_URL: "mysql"
   KAFKA_URL: "kafka:9092"
   SECRET_KEY: "your-secret-key"
   ALFR3D_ENV_NAME: "Alfr3d-Cassiopeia"