apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
       containers:
       - name: kafka
         image: confluentinc/cp-kafka:7.4.0
         envFrom:
         - configMapRef:
             name: alfr3d-k8s-env
         env:
         - name: KAFKA_ZOOKEEPER_CONNECT
           value: "zookeeper-0.zookeeper.default.svc.cluster.local:2181"
         - name: KAFKA_ADVERTISED_PORT
           value: ""
         - name: KAFKA_ADVERTISED_HOST
           value: ""
         - name: KAFKA_HOST
           value: ""
         - name: KAFKA_PORT
           value: ""
         - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
           value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
         - name: KAFKA_INTER_BROKER_LISTENER_NAME
           value: "PLAINTEXT"
         - name: KAFKA_ADVERTISED_LISTENERS
           value: "PLAINTEXT://kafka-0.kafka:29092,PLAINTEXT_HOST://kafka-0.kafka:9092"
         - name: KAFKA_LISTENERS
           value: "PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092"
         - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
           value: "true"
         ports:
         - containerPort: 9092
         - containerPort: 29092