apiVersion: v1
kind: Service
metadata:
  name: alfr3d-service-speak
  labels:
    app: alfr3d-service-speak
spec:
  selector:
    app: alfr3d-service-speak
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
  type: ClusterIP
