apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-frontend
  template:
    metadata:
      labels:
        app: service-frontend
    spec:
       containers:
       - name: service-frontend
         image: alfr3d/service-frontend:latest
         imagePullPolicy: Never
         envFrom:
         - configMapRef:
             name: alfr3d-k8s-env
         ports:
         - containerPort: 8000