apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-daemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-daemon
  template:
    metadata:
      labels:
        app: service-daemon
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox
        command: ['sh', '-c', 'until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done;']
      containers:
      - name: service-daemon
        image: alfr3d/service-daemon:latest
        envFrom:
        - configMapRef:
            name: alfr3d-k8s-env